version: 2
updates:
  # For Gradle, update dependencies and plugins to the latest non-major version
  - package-ecosystem: "gradle"
    groups:
      dependencies:
        patterns:
          - "*"
    directory: "/scalardl-cleanup"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  # For GitHub Actions, update all actions on the default branch
  - package-ecosystem: "github-actions"
    groups:
      actions on branch master:
        patterns:
          - "*"
    directory: "/"
    schedule:
      interval: "weekly"
