pipeline {
  agent any
  stages {
    stage('Blah') {
      steps {
        sh 'echo $(pwd)'
        sh 'echo $(ls)'
      }
    }
    stage('Build') {
      steps {
        sh './gradlew assemble'
      }
    }
    stage('Test') {
      steps {
        sh './gradlew test'
      }
    }
  }
  post {
    always {
      mail(to: 'siyopao@gmail.com', from: 'jenkins', subject: 'Build finished', body: 'Hi there!')
    }
    //failure {}
  }
}
