pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh './gradlew assemble'
      }
    }
    state('Test') {
      steps {
        sh './gradlew test'
      }
    }
    post {
      always {
              mail(to: 'siyopao@gmail.com', from: 'jenkins', subject: 'Build finished', body: 'Hi there!')
            }
      failure {}
    }
  }
}
