#!/bin/bash

docker-compose -f src/integration-test/resources/docker-compose-e2e.yml up -d --build
until docker exec explorer.explorer-e2e cqlsh 2> /dev/null ; do
    sleep 2
done
docker exec explorer.explorer-e2e cqlsh -f /create_schema.cql --request-timeout=30
gradle integrationTest -i
docker-compose -f src/integration-test/resources/docker-compose-e2e.yml down -v
