scalar.dl.client.server.host=127.0.0.1
scalar.dl.client.auditor.enabled=true
scalar.dl.client.auditor.host=127.0.0.1
scalar.dl.client.authentication.method=hmac
scalar.dl.client.entity.id=e2e-client
scalar.dl.client.entity.identity.hmac.secret_key=e2e-client-hmac-secret-disposable-0123456789
