name: Explorer-CI

on:
  push:
    paths:
      - 'explorer/**'

jobs:
  Explorer:
    runs-on: ubuntu-latest

    steps:
    - name: Clone scalardl-tools repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Explorer
      run: |
        cd explorer
        ./gradlew assemble

    - name: Test Explorer
      run: |
        cd explorer
        ./gradlew test
