# When we push a new SNAPSHOT image, the old SNAPSHOT image remains as an untagged
# image in GitHub Packages. We remove those untagged images by using this workflow.

name: Remove untagged images

on:
  schedule:
    # UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  remove-untagged-container-images:
    runs-on: ubuntu-latest

    steps:
      - name: scalardl-cleanup
        uses: actions/delete-package-versions@v5
        with:
          package-name: scalardl-cleanup
          package-type: container
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 0
          token: ${{ secrets.CR_PAT }}
